//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoiseLab.PolyGen.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoiseLab.PolyGen.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_aspnetcore_hosting_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_aspnetcore_hosting_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_aspnetcore_hosting_abstractions_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_aspnetcore_hosting_abstractions_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_aspnetcore_http_abstractions_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_aspnetcore_http_abstractions_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_aspnetcore_mvc_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_aspnetcore_mvc_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_aspnetcore_mvc_abstractions_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_aspnetcore_mvc_abstractions_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_aspnetcore_mvc_core_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_aspnetcore_mvc_core_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_aspnetcore_mvc_viewfeatures_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_aspnetcore_mvc_viewfeatures_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_aspnetcore_server_iisintegration_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_aspnetcore_server_iisintegration_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_aspnetcore_server_kestrel_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_aspnetcore_server_kestrel_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_entityframeworkcore_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_entityframeworkcore_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_entityframeworkcore_relational_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_entityframeworkcore_relational_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_entityframeworkcore_sqlserver_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_entityframeworkcore_sqlserver_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_extensions_configuration_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_extensions_configuration_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_extensions_configuration_abstractions_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_extensions_configuration_abstractions_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_extensions_configuration_binder_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_extensions_configuration_binder_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_extensions_configuration_environmentvariables_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_extensions_configuration_environmentvariables_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_extensions_configuration_fileextensions_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_extensions_configuration_fileextensions_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_extensions_configuration_json_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_extensions_configuration_json_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] microsoft_extensions_dependencyinjection_abstractions_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("microsoft_extensions_dependencyinjection_abstractions_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] netstandard_library_2_0_0 {
            get {
                object obj = ResourceManager.GetObject("netstandard_library_2_0_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] system_componentmodel_annotations_4_4_0 {
            get {
                object obj = ResourceManager.GetObject("system_componentmodel_annotations_4_4_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
